openapi: "3.0.3"
info:
  title: "KeyLink System: Frontend"
  description: |
    This API provides information associated with KeyLink System.
  version: "Keylink Frontend Renewal Team"
  contact:
    url: "https://mdc-agile.ubsbank.com/confluence/display/RSAY1074/KeyLink+FrontEnd+Renewal"
    email: "key-life@ubs.com"
  license:
    name: "UBS AG License"
    url: "https://www.ubs.com"
servers:
  - url: "https://ebanking-chl.tsl.tsl-zh.ubstest.net/app/K3/3/KeyLinkFrontendAPI/v1"
tags:
  - name: "Account API"
paths:
  /api/accounts:
    get:
      tags:
        - "Account API"
      summary: "Retrieves accounts"
      description: |
        Returns accounts based on query parameters. Encoded Keylink Session objects must be provided as a request header.
      operationId: "getAccounts"
      parameters:
        - name: "category"
          in: "query"
          description: "Category of the accounts"
          required: true
          schema:
            type: "string"
          example: "EDO_TRANSACTION"
          enum:
            - "MAILBOX"
            - "CASH_ALL"
            - "EDO_TRANSACTION"
            - "FINAL_DAY_TRANSACTION"
            - "PAYMENT"
            - "NOTICE_TO_RECEIVE"
            - "SECURITY_POSITIONS"
            - "SETTLEMENT_TRANSACTION"
            - "SETTLEMENT_INSTRUCTION"
            - "SETTLEMENT_ISSUED_CHECK"
            - "CASH_LIQUIDITY_MANAGER"
            - "CORPORATE_CORPORATE_EVENTS"
            - "CIB_AFAD"
            - "TASK_MONITOR"
      responses:
        200:
          description: "Accounts search response"
          content:
            application/json:
              schema:
                title: "AccountsResponse"
                type: "object"
                properties:
                  accounts:
                    type: "array"
                    items:
                      $ref: "#/components/schemas/Account"
        400:
          description: |
            Bad request. The request validation failed due to invalid or missing parameters.
          content:
            application/problem+json; charset=utf-8:
              $ref: "#/components/schemas/BadRequestValidationFailed"
        403:
          description: |
            Forbidden. You are not authorized to use this function.
          content:
            application/problem+json; charset=utf-8:
              $ref: "#/components/schemas/Forbidden"
components:
  schemas:
    Account:
      type: "object"
      properties:
        accountInfo:
          $ref: "#/components/schemas/AccountInfo"
        masterAccountsDescription:
          type: "string"
          description: "Master Accounts description"
          example: "Test Account ICC APAC 1"
    AccountInfo:
      type: "object"
      properties:
        type:
          type: "string"
          description: "Account type"
          example: "Accounts Type"
        currency:
          type: "string"
          description: "Currency"
          example: "Currency"
        maxTransactionAmount:
          type: "string"
          description: "Maximum transaction amount"
          example: "75000.00"
        secondVerifyAmount:
          type: "string"
          description: "Maximum transaction amount for the second verification"
          example: "65000.00"
        transferType:
          type: "string"
          description: "Transfer type"
          example: "MT101"
        bank:
          $ref: "#/components/schemas/Bank"
        byOrderOf:
          $ref: "#/components/schemas/ByOrderOfEntity"
    AccountData:
      type: "object"
      properties:
        accountNumber:
          type: "string"
          description: "Identifier of the account"
          example: "CH2300760097377472"
        accountDescription:
          type: "string"
          description: "Description of the account"
          example: "Test Account"
        sensitiveCategory:
          type: "string"
          description: "Key attributes of the accounts"
          example: "by-sensitive-identifier"
    ByOrderOfEntity:
      type: "object"
      properties:
        id:
          type: "string"
          description: "Id of the ordering customer"
        description:
          type: "string"
          description: "Description of the ordering customer"
    BadRequestValidationFailed:
      type: "object"
      description: |
        Problem to describe: a customer ordering a cash instruction in swift format
      properties:
        type:
          type: "string"
          description: "A URI reference that identifies the problem type."
          example: "/api/status-codes/validation-error"
        status:
          type: "integer"
          minimum: 400
          maximum: 400
          description: "The HTTP status code."
        title:
          type: "string"
          description: |
            A short, human-readable, translated (see the `Accept-Language` request header) summary
            of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem,
            except for purposes of localisation (e.g., using proactive content negotiation; see
            [RFC7231], Section 3.4).
          example: "The request is invalid."
        detail:
          type: "string"
          description: |
            A human-readable, translated (see the `Accept-Language` request header) explanation
            specific to this occurrence of the problem.
          example: "Unexpected value for foo."
        invalidParams:
          type: "array"
          items:
            type: "object"
            properties:
              name:
                type: "string"
                description: "Parameter name of resource to map reason message."
                example: "foo"
              reason:
                type: "string"
                description: |
                  Translated explanation to the user how to resolve the issue.
                example: "must be a positive integer"
      description: "Bad request; validation failed."
    Forbidden:
      type: "object"
      properties:
        type:
          type: "string"
          description: "A URI reference that identifies the problem type."
          example: "/api/status-codes/forbidden"
        status:
          type: "integer"
          description: "The HTTP status code."
          example: 403
        title:
          type: "string"
          description: |
            A short, human-readable, translated (see the `Accept-Language` request header) summary
            of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem,
            except for purposes of localisation (e.g., using proactive content negotiation; see
            [RFC7231], Section 3.4).
          example: "You are not authorized to use this function."
        detail:
          type: "string"
          description: "Forbidden."
    Bank:
      type: "object"
      properties:
        id:
          type: "string"
          description: "SWIFT BIC of the bank"
          example: "UBSWCHZHXXX"
        name:
          type: "string"
          description: "Name of the bank"
          example: "UBS Switzerland AG"
        address:
          type: "string"
          description: "Address where the bank is located"
          example: "Wall Street 1"
        city:
          type: "string"
          description: "City where the bank is located."
          example: "Zurich"
        backValueDays:
          type: "integer"
          description: "How many days in the past can the cash instruction's value date be."
          example: 3
        forwardValueDays:
          type: "integer"
          description: "How many days in the future can the cash instruction's value date be."
          example: 30